
name: 'Docker Build and Push from Branch'

on:
  push:
    branches-ignore:
    - main

env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  AZURE_WEBAPP_PACKAGE_PATH: .

jobs:
  docker:
    name: 'Docker Build and push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -f Dockerfile -t ${{ secrets.REGISTRY_NAME }}/festive-tech:${GITHUB_REF##*/} --build-arg BRANCH=${GITHUB_REF##*/}
          docker push ${{ secrets.REGISTRY_NAME }}/festive-tech:${GITHUB_REF##*/}